.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. moneytreexe_qt test_moneytreexe_qt
clean: FORCE
	$(MAKE) -C .. moneytreexe_qt_clean test_moneytreexe_qt_clean
check: FORCE
	$(MAKE) -C .. test_moneytreexe_qt_check
moneytreexe-qt moneytreexe-qt.exe: FORCE
	 $(MAKE) -C .. moneytreexe_qt
